version: '3.8'

services:
  hason:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hason.rule=Host(`localhost`)"
      - "traefik.http.services.hason.loadbalancer.server.port=80"

  # Optional: Add a simple health monitoring service
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup
    restart: unless-stopped