name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      
      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Setup jq and WASM files
        run: nix run .#copy-wasm-to-app
      
      - name: Setup npm and install dependencies
        uses: ./.github/actions/setup-install
      
      - name: Run all tests
        run: npm run test:all
      
      - name: Build application
        run: npm run build
      
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: true
          skip-commit: true
          skip-tag: true
          output-file: false
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: Release ${{ github.event.inputs.version || github.ref_name }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
          generate_release_notes: true
      
      - name: Deploy to production
        run: |
          echo "Deploying version ${{ github.event.inputs.version || github.ref_name }} to production"
          # Add deployment steps here
