name: "E2E Tests"

on:
  pull_request:
    branches:
      - main

jobs:
  build-wasm:
    name: Build WASM Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Cache WASM files
        id: cache-wasm
        uses: actions/cache@v4
        with:
          path: |
            packages/app/public/jq*.js
            packages/app/public/jq*.wasm
            packages/jq-hason/src/wasm/jq*.js
            packages/jq-hason/src/wasm/jq*.wasm
          key: jq-wasm-${{ hashFiles('flake.nix', 'flake.lock', 'packages/app/public/jq-version.json') }}

      - name: Install Nix
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-

      - name: Build WASM files
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        run: |
          nix build .#jq-wasm
          mkdir -p packages/app/public packages/jq-hason/src/wasm
          cp -v result/lib/jq*.js packages/app/public/
          cp -v result/lib/jq*.wasm packages/app/public/
          cp -v result/lib/jq*.js packages/jq-hason/src/wasm/
          cp -v result/lib/jq*.wasm packages/jq-hason/src/wasm/

      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jq-wasm-files
          path: |
            packages/app/public/jq*.js
            packages/app/public/jq*.wasm
            packages/jq-hason/src/wasm/jq*.js
            packages/jq-hason/src/wasm/jq*.wasm
            packages/app/public/jq-version.json

  unit-tests:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    needs: build-wasm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download WASM artifacts
        uses: actions/download-artifact@v5
        with:
          name: jq-wasm-files
          path: ./

      - name: Setup pnpm and install dependencies
        uses: ./.github/actions/setup-install

      - name: Build packages
        run: pnpm build:packages

      - name: Run unit and integration tests
        run: NODE_ENV=test pnpm --filter=app test

  e2e-tests:
    name: E2E Tests (Preview Build)
    runs-on: ubuntu-latest
    needs: build-wasm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download WASM artifacts
        uses: actions/download-artifact@v5
        with:
          name: jq-wasm-files
          path: ./

      - name: Setup pnpm and install dependencies
        uses: ./.github/actions/setup-install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build Vite application
        run: pnpm run build

      - name: Start preview server and run E2E tests
        run: |
          # Start preview server in background
          pnpm run preview &
          PREVIEW_PID=$!

          # Wait for server to start
          timeout 30 bash -c 'until curl -s http://localhost:4173 > /dev/null; do sleep 1; done'

          # Run E2E tests against preview server
          TEST_URL=http://localhost:4173 pnpm run test:e2e

          # Clean up
          kill $PREVIEW_PID